version: "3.9"

services:
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/neo4j2023
    container_name: neo4j_db
    networks:
      - local
    ports:
     - 7474:7474
     - 7687:7687
    volumes:
      - neo4j_db_data:/data
      - neo4j_db_logs:/logs

networks:
  local:
    driver: bridge
    name: neo4j_network

volumes:
  neo4j_db_data:
    driver: local
    name: neo4j_db_data
  neo4j_db_logs:
    driver: local
    name: neo4j_db_logs
